# Generated by Django 4.2.3 on 2023-07-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='status',
            field=models.BooleanField(default=True, help_text='Situação da consulta', verbose_name='Status'),
        ),
    ]
